using CarRentals_MVVM.ViewModels;

namespace CarRentals_MVVM.Models
{
    /// <summary>
    /// Represents a single car in the rental fleet.
    /// Inherits ObservableObject so the UI auto-updates when any property changes.
    /// Connected to: CarDataService (data source), BrowseCarsViewModel (display),
    /// AddCarViewModel (create/delete), FleetStatusWindow (read-only view).
    /// </summary>
    public class CarModel : ObservableObject
    {
        // ── Private backing fields ─────────────────────────────────────────────

        private string _carId = string.Empty;
        private string _name = string.Empty;
        private string _category = string.Empty;
        private string _fuelType = string.Empty;
        private string _status = "Available";
        private decimal _pricePerHour;
        private string _imageUrl = string.Empty;
        private string[] _availableColors = [];


        // ── Public properties with change notification ─────────────────────────

        /// <summary>
        /// Unique identifier for the car (e.g. "C001").
        /// Auto-generated by AddCarViewModel.GenerateNextId().
        /// </summary>
        /// 
        public string CarId
        {
            get => _carId;
            set
            {
                if (_carId != value)
                {
                    _carId = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// Display name of the car (e.g. "Toyota Camry").
        /// </summary>
        public string Name
        {
            get => _name;
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// Vehicle category: "Sedan", "SUV", or "Van".
        /// Used for filtering in BrowseCarsViewModel.
        /// </summary>
        public string Category
        {
            get => _category;
            set
            {
                if (_category != value)
                {
                    _category = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// Fuel type: "Standard Engine", "EV", or "Hybrid Engine".
        /// Used for filtering in BrowseCarsViewModel.
        /// </summary>
        public string FuelType
        {
            get => _fuelType;
            set
            {
                if (_fuelType != value)
                {
                    _fuelType = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// Current car status: "Available", "Rented", or "Maintenance".
        /// Changed to "Rented" by BrowseCarsViewModel.ConfirmCommand after booking.
        /// Controls visibility in customer browse view.
        /// </summary>
        public string Status
        {
            get => _status;
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// Rental cost per hour in USD.
        /// Used in BrowseCarsViewModel to compute BasePrice, Deposit, and TotalDue.
        /// </summary>
        public decimal PricePerHour
        {
            get => _pricePerHour;
            set
            {
                if (_pricePerHour != value)
                {
                    _pricePerHour = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// Direct URL to the car's image (e.g. an Imgur link).
        /// Displayed in BrowseCarsWindow cards and color picker page.
        /// Leave empty for placeholder gradient display.
        /// </summary>
        public string ImageUrl
        {
            get => _imageUrl;
            set
            {
                if (_imageUrl != value)
                {
                    _imageUrl = value;
                    OnPropertyChanged();
                }
            }
        }

        /// <summary>
        /// List of color options available for this car.
        /// Displayed as color swatches on Page 2 of BrowseCarsWindow.
        /// </summary>
        public string[] AvailableColors
        {
            get => _availableColors;
            set
            {
                if (_availableColors != value)
                {
                    _availableColors = value;
                    OnPropertyChanged();
                }
            }
        }
    }
}